info:
  os: Centos
service:
  name: users
spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQL9Dialect
    properties.hibernate.temp.use_jdbc_metadata_defaults: false

  datasource:
    platform : postgres
    url: jdbc:postgresql://localhost:5433/dofustuff?currentSchema=sch_dofustuff
    username: dofustuff
    password: "DofusStuff01*"
    driverClassName: org.postgresql.Driver
network:
  services:
    media:
      url: http://localhost:8081/medias/metadata
      enabled: false
      extractor: true
eureka:
  instance:
    prefer-ip-address: true
    appname: @component.name@
    instanceId: @component.name@:${spring.application.instance_id:${random.value}}
    hostname: localhost
  client:
    enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://@eureka.host@:@eureka.port@/eureka/
  ribbon:
    enabled: true